### PR TITLE
first go at making it work on MacOS

### PR DESCRIPTION
**Pull request by andremv**
Hi @dekuNukem!

Thank you for all the hard work you put into the duckyPad.

I played around with the autoprofile feature and made it work on MacOS.
There's a catch though ... it requires you to run the application as root to write to the pad. Also the UI needs a bit of a tweak.

I will spend some more time on it this week, maybe I can improve it.

Screenshot 2021-05-10 at 21 42 41

Screenshot 2021-05-10 at 21 43 30

### CODE REVIEW

**Comment by dekuNukem** [comment]
Thank you very much for the contribution! I'm a bit busy today, but I'll give it a go tomorrow. 👍

**Comment by dekuNukem** [comment]
I gave it a go and it works, although on macOS it can't seem to get the window title apart from itself, I guess that's a limitation of macOS?

Also, did you get the HID to work on your mac? i.e. did it manage to connect to duckyPad and control it?

**Comment by andremv** [comment]
Some of the windows in macOS don't have a title (Google Chrome for instance), I'm assuming that's a limitation.

I only managed to make the HID work by running it with sudo which is far from ideal. Enabling the app in Security & Privacy > Privacy > Accessibility didn't seem to do anything but I will invest some more time this evening and get back to you.

**Comment by andremv** [comment]
Unfortunately I couldn't find any way to write to HID on Mac without sudo. It seems like you would have to write a driver for this to work properly.

I haven't looked at the firmware yet but ... how hard it is to expose a serial port?

**Comment by dekuNukem** [comment]
I'm afraid there isn't enough space on the microcontroller for an additional USB serial interface, the RAM is like 95% full.

Anyway, I'll probably have a few more people test it, and see how it goes. Thank you very much for the contribution!

**Comment by harryjubb** [comment]
@andremv @dekuNukem

Repeat from Discord, here for posterity!

The window titles work properly if you give the app (or the terminal you're running the app from) "Screen Recording" permission in System Preferences under the "Privacy" tab in "Security & Privacy".

Without:

image

With:

image

Happy to PR an update to the docs

**Comment by harryjubb** [comment]
@andremv separate but related issue: have you had any issues on OS X where keypresses on the pad aren't picked up by OS X while the autoswitcher is running?

I get it consistently and it just prevents me from using the autoswitcher entirely.

I'm putting together a PR that fixes it for me, but wanted to check if anyone else is having the same issue. I get the same with the configurator as well. AFAICT it's an issue with the autoswitcher (and configurator) blocking the OS X kernel from reading from the pad [as described in https://github.com/trezor/cython-hidapi/issues/48#issuecomment-385971854]. Refactoring to open / close the connection for each read / write seems to work.

Will update here when I've got a PR together

**Pull request merged**
